services:
  web:
    container_name: mylandingpage
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/
    command: ["tail", "-f", "/dev/null"]
    env_file: .env

  db:
    container_name: my_db
    image: postgres:18.0-alpine3.22
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file: .env

volumes:
  db_data: